- name: install webserver package
  hosts: webserver
  become: true
  remote_user: centos
  gather_facts: false
  roles:
  - webservers

  tasks:
  - name: start tomcat
    command: 'sh /opt/tomcat/bin/startup.sh'
    ignore_errors: yes 
  
- name: manage users
  hosts: localhost
  become: true
  gather_facts: false
  connection: local
  roles:
  - webservers
