- name: install webserver package
  hosts: webserver
  become: true
  remote_user: centos
  gather_facts: false
  
  handlers:
  - name: restart_server
    service:
       name: "{{ service_name }}"
       state: restarted  
  
  tasks:
  - name: install webserver
    yum:
       name: "{{ package_name }}"
       state: present
  - name: manage service
    service:
       name: "{{ service_name }}"
       state: started
  - name: deploy site
    copy:
       src: index.html
       dest: /var/www/html
  - name: deploy template
    template:
       src: index.html
       dest: /var/www/html
    notify:
    - restart_server

- name: manage users
  hosts: localhost
  become: true
  gather_facts: false
  connection: local

  tasks:
  - name: create user
    user:
      name: "{{ user_name }}"
      state: present

